{% set pkgname = "gnuplot" %}
{% set version = "5.2.0" %}
{% set sha256 = "7dfe6425a1a6b9349b1fb42dae46b2e52833b13e807a78a613024d6a99541e43" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ pkgname }}/files/{{ pkgname }}/{{ version }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/term_include.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - toolchain3
    - pkgconfig
    - ncurses 5.9
    - readline 7.0
    - libgd
    - cairo 1.14.*
    - pango 1.40.*
    - qt 5.6.*
    - freetype 2.8.1
    - glib 2.55.*
  run:
    - ncurses 5.9
    - readline 7.0
    - libgd
    - cairo 1.14.*
    - pango 1.40.*
    - qt 5.6.*
    - freetype 2.8.1
    - glib 2.55.*

test:
  files:
    - test-data.txt
  commands:
    - gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
    - gnuplot -e "set terminal png"
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://github.com/gnuplot/gnuplot
  license: Gnuplot
  license_file: Copyright
  summary: Gnuplot, plotting from command line

extra:
  recipe-maintainers:
    - croth1
