appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ORyq43tGKcSmjC+XzwJ4Cr3njEZo+ASUfWzmXz9xGLQbkrA0avUeiStwP9GnstblU90Iz8ABrNhi4+3UnvChBJ41gqUov1EhjhSyv7wT2TZ6yslbqU+zPPBg4nQOlm67ozDmP79PWG4jBzzHAZW+S6bdWRDglMgSeey+4dBfBPy6oqL9WQaOrYrQMYwsZotnu62p2bsaSPmemYPKRcXmBMF9/fMFtkByosKxWD5CsppAxhQNzvuASh5OAUJiQPkurHJ9EeYxN9uZzFZV4IxioGaOw5eP3nwvoq2aKOk/ZUV7qMn4FLW73j1fMz1HLh2TPJ+K8eofMD07g61ZyCS/QMsuqowPOF2rJQpFbwDEgJPIw4wC3GR69XTR4q2lAKxYK6hqZw3fy3W9Pqq4hCBk27sIZwP+yrI5irQ3M2M85mRX8OJVdRf6bgG8D+DMIhQHclHBclyjSFlEqMyJBnQRSA2FFDIek7yUPGo7qMuK/g+43mc1tvt9FOy4KrX605CAAH78mUnUKM79Ep+I1FrCAgwXc3phWzmfc1Ur5oiClcmAYpFiiKuIhqAh+EvH1aGDQYhdubSsKTt0gmRM4NQ4WkXOP25i6VRiBUR6+yjs+2WdU9beLyHPsVnod7WO9un1RsIBIsQvuDNlOq9MwpVjz4uIYxrTDKR8+Ey4gEE04mI=}
