travis:
  secure:
    BINSTAR_TOKEN: F4zX5IKdy4ztfBcx+XQd6nQEKt7uqHiXzrrJi7F0zSe0IPg4uHuUYRydO6R7c9+F8X+lMu4d3zvLbrREnj3+IiVR4Sbj9Rc0ZxxDCag0//irV1ITN+2jzEdPWIFudHloslbcU+3tOruKRoIqgX9QnuYxYoZob8m3Ozy/Zat51UKP6hW4ZMhEunY4ZL09atYhDforqS2ZSHwIOEoCmIRc0JPASwCSqWz2iLJtHomhaDrYfKZMI+HEh3BtHGFL0vNJ6lyEJFpSd9Is09jf0nGlPOQ46HWcmhaZkqMMNHvsMw88kDovWjul4gBkany7tCPFiJg7+6WOx8RNtMj8C1Of65R3rmW+iPSEg7eSrTXYfqF3shxOjkc2fR5ra8TjrLZrxTArQjTYhNvDpAU7zdp/308SHHO3gKDhbxZnvyMICMHVmaI2hLI1n9Nb5pRDmyl2nEdyozIjjO2UUQfytmk5vhZxr2Re7rgyawTvw/fM159A8rtYkOh1Y9g0g8lOu3R6/Vc6nJtY8rbExga6+YOY8hH8o6DHM6HUCLVbb+Dwsd3TZjTC2SqWjgT90GsGmeSeUabjgQKWWlY4K0atW3XaI/5nFTW1qxqvRWzmGlaNJdq3hifiG50S3PUeDqR2DVf6+lLplMiIL/Xl8GDveHWbzyTML3WnVT/Sv/5YPVgQQwY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
